import type { ResolvedVibe, VibePreset } from '../types/vibe';

/**
 * Fully-resolved aesthetics. These are the single source of truth for what each
 * semantic preset "feels" like; `resolveVibe` layers user overrides on top.
 */
export const VIBE_PRESETS: Record<VibePreset, ResolvedVibe> = {
  messy_sketch: {
    preset: 'messy_sketch',
    roughness: 1.6,
    bowing: 1.5,
    strokeWidth: 1.5,
    stroke: '#1f2937',
    fill: '#1f2937',
    fillStyle: 'hachure',
    fillWeight: 1,
    hachureAngle: -41,
    hachureGap: 4,
    curveStepCount: 9,
    curveTightness: 0,
    disableMultiStroke: false,
    seed: 1,
    fontFamily: '"Comic Neue", "Comic Sans MS", "Segoe Print", cursive',
    fontSize: 14,
  },
  clean_blueprint: {
    preset: 'clean_blueprint',
    roughness: 0.6,
    bowing: 0.4,
    strokeWidth: 1.25,
    stroke: '#1d4ed8',
    fill: '#3b82f6',
    fillStyle: 'cross-hatch',
    fillWeight: 0.5,
    hachureAngle: 45,
    hachureGap: 6,
    curveStepCount: 14,
    curveTightness: 0,
    disableMultiStroke: true,
    seed: 7,
    fontFamily: '"Cousine", "Courier New", ui-monospace, monospace',
    fontSize: 13,
  },
  chaotic_notebook: {
    preset: 'chaotic_notebook',
    roughness: 2.8,
    bowing: 2.5,
    strokeWidth: 2,
    stroke: '#111827',
    fill: '#f59e0b',
    fillStyle: 'zigzag',
    fillWeight: 1.5,
    hachureAngle: 17,
    hachureGap: 3,
    curveStepCount: 6,
    curveTightness: 0.2,
    disableMultiStroke: false,
    seed: 13,
    fontFamily: '"Gloria Hallelujah", "Comic Sans MS", "Segoe Print", cursive',
    fontSize: 15,
  },
  pencil: {
    preset: 'pencil',
    roughness: 1.2,
    bowing: 1,
    strokeWidth: 0.9,
    stroke: '#4b5563',
    fill: '#9ca3af',
    fillStyle: 'hachure',
    fillWeight: 0.6,
    hachureAngle: -35,
    hachureGap: 3,
    curveStepCount: 11,
    curveTightness: 0,
    disableMultiStroke: false,
    seed: 3,
    fontFamily: '"Caveat", "Segoe Print", "Bradley Hand", cursive',
    fontSize: 13,
  },
  marker: {
    preset: 'marker',
    roughness: 1,
    bowing: 0.8,
    strokeWidth: 3.5,
    stroke: '#0f172a',
    fill: '#38bdf8',
    fillStyle: 'solid',
    fillWeight: 2,
    hachureAngle: 0,
    hachureGap: 5,
    curveStepCount: 10,
    curveTightness: 0,
    disableMultiStroke: true,
    seed: 5,
    fontFamily: '"Permanent Marker", "Marker Felt", cursive',
    fontSize: 15,
  },
  ink: {
    preset: 'ink',
    roughness: 0.8,
    bowing: 0.6,
    strokeWidth: 1.6,
    stroke: '#0b1020',
    fill: '#1e293b',
    fillStyle: 'cross-hatch',
    fillWeight: 0.7,
    hachureAngle: 41,
    hachureGap: 5,
    curveStepCount: 13,
    curveTightness: 0,
    disableMultiStroke: false,
    seed: 9,
    fontFamily: '"Spectral", "Iowan Old Style", Georgia, serif',
    fontSize: 14,
  },
  crayon: {
    preset: 'crayon',
    roughness: 2.2,
    bowing: 1.8,
    strokeWidth: 2.8,
    stroke: '#7c2d12',
    fill: '#fb923c',
    fillStyle: 'zigzag',
    fillWeight: 2.5,
    hachureAngle: 25,
    hachureGap: 4,
    curveStepCount: 7,
    curveTightness: 0.15,
    disableMultiStroke: false,
    seed: 21,
    fontFamily: '"Schoolbell", "Comic Sans MS", "Chalkboard", cursive',
    fontSize: 15,
  },
  // Leonardo's notebooks: fine, confident iron-gall (sepia) pen on a warm
  // sienna cross-hatch. The negative hachure angle mimics his left-handed
  // shading, which slants top-left → bottom-right. Seed = his birth year.
  davinci_journal: {
    preset: 'davinci_journal',
    roughness: 1,
    bowing: 0.7,
    strokeWidth: 1.1,
    stroke: '#4a3520',
    fill: '#b08a55',
    fillStyle: 'cross-hatch',
    fillWeight: 0.45,
    hachureAngle: -52,
    hachureGap: 7,
    curveStepCount: 14,
    curveTightness: 0,
    // Single-stroke so connectors and outlines read as one confident pen line
    // rather than a doubled, scratchy one. (Fill hatching is unaffected.)
    disableMultiStroke: true,
    seed: 1452,
    fontFamily: '"EB Garamond", "Iowan Old Style", "Palatino Linotype", Palatino, "Book Antiqua", Georgia, serif',
    fontSize: 14,
    // Aged-parchment page so the ink has somewhere to sit; this also drives the
    // node fill and the gap behind zone labels, so no stark-white seams show.
    background: '#f2e8cf',
  },
  // Classic drafting blueprint: crisp white/cyan ink on a deep blue page — the
  // inverse of clean_blueprint.
  blueprint_dark: {
    preset: 'blueprint_dark',
    roughness: 0.6,
    bowing: 0.4,
    strokeWidth: 1.25,
    stroke: '#dbeafe',
    fill: '#93c5fd',
    fillStyle: 'cross-hatch',
    fillWeight: 0.5,
    hachureAngle: 45,
    hachureGap: 6,
    curveStepCount: 14,
    curveTightness: 0,
    disableMultiStroke: true,
    seed: 23,
    fontFamily: '"Cousine", "Courier New", ui-monospace, monospace',
    fontSize: 13,
    background: '#0e3a66',
  },
  // Chalk on a slate board: dusty white strokes and hachure, casual hand.
  chalkboard: {
    preset: 'chalkboard',
    roughness: 1.4,
    bowing: 1.1,
    strokeWidth: 1.4,
    stroke: '#eef0e9',
    fill: '#cdd3c8',
    fillStyle: 'hachure',
    fillWeight: 0.7,
    hachureAngle: -30,
    hachureGap: 4,
    curveStepCount: 9,
    curveTightness: 0,
    disableMultiStroke: false,
    seed: 28,
    fontFamily: '"Schoolbell", "Comic Sans MS", cursive',
    fontSize: 15,
    background: '#2e3b35',
  },
  // Neon signage: bright cyan tubes and a fuchsia cross-hatch on near-black.
  neon: {
    preset: 'neon',
    roughness: 0.5,
    bowing: 0.3,
    strokeWidth: 1.7,
    stroke: '#22d3ee',
    fill: '#d946ef',
    fillStyle: 'cross-hatch',
    fillWeight: 0.6,
    hachureAngle: 45,
    hachureGap: 7,
    curveStepCount: 16,
    curveTightness: 0,
    disableMultiStroke: true,
    seed: 31,
    fontFamily: '"Orbitron", ui-monospace, monospace',
    fontSize: 13,
    background: '#0a0a12',
  },
  // Comic book: thick black ink outlines and bold solid fills, punchy lettering.
  comic_book: {
    preset: 'comic_book',
    roughness: 0.9,
    bowing: 0.6,
    strokeWidth: 2.8,
    stroke: '#111111',
    fill: '#ef4444',
    fillStyle: 'solid',
    fillWeight: 2,
    hachureAngle: 0,
    hachureGap: 5,
    curveStepCount: 12,
    curveTightness: 0,
    disableMultiStroke: true,
    seed: 37,
    fontFamily: '"Bangers", "Comic Sans MS", cursive',
    fontSize: 16,
    background: '#fffdf6',
  },
};

export const DEFAULT_VIBE: VibePreset = 'messy_sketch';
