import type { ResolvedVibe, VibePreset } from '../types/vibe';

/**
 * Fully-resolved aesthetics. These are the single source of truth for what each
 * semantic preset "feels" like; `resolveVibe` layers user overrides on top.
 */
export const VIBE_PRESETS: Record<VibePreset, ResolvedVibe> = {
  messy_sketch: {
    preset: 'messy_sketch',
    roughness: 1.6,
    bowing: 1.5,
    strokeWidth: 1.5,
    stroke: '#1f2937',
    fill: '#1f2937',
    fillStyle: 'hachure',
    fillWeight: 1,
    hachureAngle: -41,
    hachureGap: 4,
    curveStepCount: 9,
    curveTightness: 0,
    disableMultiStroke: false,
    seed: 1,
    fontFamily: '"Comic Sans MS", "Segoe Print", cursive',
    fontSize: 14,
  },
  clean_blueprint: {
    preset: 'clean_blueprint',
    roughness: 0.6,
    bowing: 0.4,
    strokeWidth: 1.25,
    stroke: '#1d4ed8',
    fill: '#3b82f6',
    fillStyle: 'cross-hatch',
    fillWeight: 0.5,
    hachureAngle: 45,
    hachureGap: 6,
    curveStepCount: 14,
    curveTightness: 0,
    disableMultiStroke: true,
    seed: 7,
    fontFamily: '"Courier New", ui-monospace, monospace',
    fontSize: 13,
  },
  chaotic_notebook: {
    preset: 'chaotic_notebook',
    roughness: 2.8,
    bowing: 2.5,
    strokeWidth: 2,
    stroke: '#111827',
    fill: '#f59e0b',
    fillStyle: 'zigzag',
    fillWeight: 1.5,
    hachureAngle: 17,
    hachureGap: 3,
    curveStepCount: 6,
    curveTightness: 0.2,
    disableMultiStroke: false,
    seed: 13,
    fontFamily: '"Comic Sans MS", "Segoe Print", cursive',
    fontSize: 15,
  },
  pencil: {
    preset: 'pencil',
    roughness: 1.2,
    bowing: 1,
    strokeWidth: 0.9,
    stroke: '#4b5563',
    fill: '#9ca3af',
    fillStyle: 'hachure',
    fillWeight: 0.6,
    hachureAngle: -35,
    hachureGap: 3,
    curveStepCount: 11,
    curveTightness: 0,
    disableMultiStroke: false,
    seed: 3,
    fontFamily: '"Segoe Print", "Bradley Hand", cursive',
    fontSize: 13,
  },
  marker: {
    preset: 'marker',
    roughness: 1,
    bowing: 0.8,
    strokeWidth: 3.5,
    stroke: '#0f172a',
    fill: '#38bdf8',
    fillStyle: 'solid',
    fillWeight: 2,
    hachureAngle: 0,
    hachureGap: 5,
    curveStepCount: 10,
    curveTightness: 0,
    disableMultiStroke: true,
    seed: 5,
    fontFamily: '"Marker Felt", "Comic Sans MS", cursive',
    fontSize: 15,
  },
  ink: {
    preset: 'ink',
    roughness: 0.8,
    bowing: 0.6,
    strokeWidth: 1.6,
    stroke: '#0b1020',
    fill: '#1e293b',
    fillStyle: 'cross-hatch',
    fillWeight: 0.7,
    hachureAngle: 41,
    hachureGap: 5,
    curveStepCount: 13,
    curveTightness: 0,
    disableMultiStroke: false,
    seed: 9,
    fontFamily: '"Iowan Old Style", Georgia, serif',
    fontSize: 14,
  },
  crayon: {
    preset: 'crayon',
    roughness: 2.2,
    bowing: 1.8,
    strokeWidth: 2.8,
    stroke: '#7c2d12',
    fill: '#fb923c',
    fillStyle: 'zigzag',
    fillWeight: 2.5,
    hachureAngle: 25,
    hachureGap: 4,
    curveStepCount: 7,
    curveTightness: 0.15,
    disableMultiStroke: false,
    seed: 21,
    fontFamily: '"Comic Sans MS", "Chalkboard", cursive',
    fontSize: 15,
  },
};

export const DEFAULT_VIBE: VibePreset = 'messy_sketch';
